// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package db

import (
	"database/sql"
)

type DeliveriesFt struct {
	ID           string `db:"id" json:"id"`
	LocationName string `db:"location_name" json:"location_name"`
}

type Delivery struct {
	ID           int64    `db:"id" json:"id"`
	Date         UnixTime `db:"date" json:"date"`
	Schedule     string   `db:"schedule" json:"schedule"`
	LocationType string   `db:"location_type" json:"location_type"`
	LocationName string   `db:"location_name" json:"location_name"`
	CreatedAt    UnixTime `db:"created_at" json:"created_at"`
}

type Import struct {
	ID          int64         `db:"id" json:"id"`
	FilePath    string        `db:"file_path" json:"file_path"`
	FileHash    int64         `db:"file_hash" json:"file_hash"`
	CreatedAt   UnixTime      `db:"created_at" json:"created_at"`
	CompletedAt *UnixTime     `db:"completed_at" json:"completed_at"`
	FailedAt    *UnixTime     `db:"failed_at" json:"failed_at"`
	Runs        sql.NullInt64 `db:"runs" json:"runs"`
}

type Sublocation struct {
	ID         int64    `db:"id" json:"id"`
	DeliveryID int64    `db:"delivery_id" json:"delivery_id"`
	Name       string   `db:"name" json:"name"`
	CreatedAt  UnixTime `db:"created_at" json:"created_at"`
}
