// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Delivery struct {
	ID           int64
	Date         UnixTime
	Schedule     string
	LocationType string
	LocationName string
	CreatedAt    UnixTime
}

type Import struct {
	ID          int64
	FilePath    string
	FileHash    int64
	CreatedAt   UnixTime
	CompletedAt sql.NullTime
	FailedAt    sql.NullTime
	Runs        sql.NullInt64
}
